name = "msgpack_gleam"
version = "0.1.0"
description = "A MessagePack implementation for Gleam"
licences = ["MIT"]

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
