name = "msgpack_codegen"
version = "0.1.0"
description = "Code generator for msgpack_gleam codecs"
licences = ["MIT"]

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glance = ">= 6.0.0 and < 7.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
argv = ">= 1.0.0 and < 2.0.0"
glint = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
